### PR TITLE
feat: add TypeScript typings file

### PR DESCRIPTION
**Pull request by acheronfail**
This PR adds a typings file so it works for consumers of this package that are using TypeScript.

### CODE REVIEW

**Comment by dnlup** [comment]
Thanks, @acheronfail for this, I am not an expert of  Typescript. If we are going to add typings, I think we should also add a check, like the fastify project does [here](https://github.com/fastify/fastify/blob/master/package.json#L10) for example.

**Comment by dnlup** [comment]
The fact that I am using `lint-staged` might complicate things a little bit because we might also have to  add an entry for the typings file in [here](https://github.com/dnlup/doc/blob/current/lint-staged.config.js#L8).

**Comment by dnlup** [comment]
Could you rebase against the latest changes in `current`? There was a misconfiguration in GitHub actions that was preventing running tests on PRs :pray:

**Comment by acheronfail** [comment]
I added some tests for the typings file, and also configured `standard` to lint it too.

However, `standard` did have a strange error when importing `EventEmitter` (says it's never used, even though it is). So I looked further into how fastify did it, and it seems that they have the linting command _and_ they also ignore the file: https://github.com/fastify/fastify/blob/ccca58e36d49cad41fc2393b408f468a486b5946/package.json#L169-L171

:man_shrugging:

**Comment by dnlup** [comment]
I see this issue is acknowledged on `standard` website (https://standardjs.com/#typescript). They are suggesting using `standardx` as a temporary solution. I would like to avoid it, at least for now, and see if this gets resolved. I suspect the people at `fastify` encountered the same problem.

I would track this in another issue but, in the meantime, we merge this. Do you see any problems with it?

Good work!

**Comment by acheronfail** [comment]
> I would track this in another issue but, in the meantime, we merge this. Do you see any problems with it?

I think it's fine as it is now - it works, and it just seems to be a linting issue. :slightly_smiling_face: 
Happy to have it merged.

**Comment by dnlup** [comment]
Published in https://github.com/dnlup/doc/releases/tag/v1.1.0

**Pull request merged**
